### ISSUE TITLE
mb_detect_encoding don't work with cyrillic (windows-1251, koi8-r)

### ISSUE THREAD

**Issue by kzgzhn** [oscarotero/html-parser#2]
Hi. 

oscarotero/Embed uses html-parser
https://github.com/oscarotero/Embed/blob/master/src/Document.php#L29

oscarotero/html-parser uses mb_detect_encoding() 
https://github.com/oscarotero/html-parser/blob/master/src/Parser.php#L26

And oscarotero/Embed doesn't work with the old encodings (windows-1251, koi8-r, etc.)

if I manually specify the encoding:

//$detected = mb_detect_encoding($html); // don't work
//$detected = 'koi8-r'; // work
$detected = 'windows-1251'; // work

Can do so 
1. Parser::parse(string $html, ?string $charset = null) 
2. and https://github.com/oscarotero/Embed/blob/master/src/Document.php#L29
specify from headers of response?

Thanks

**Comment by oscarotero** [comment]
Fair enough.
Do you want to work in a pull request?
Thanks!
